spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.rkk05.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
server:
  servlet:
    context-path: "/ip-information"


ip:
  information:
    country:
      url: "https://api.ip2country.info/ip?{ip}"

country:
  detail:
    url: "https://restcountries.eu/rest/v2/alpha/{isoCode3}"

currency:
  quote:
    url: "http://data.fixer.io/api/latest?access_key={token}"
    token: "5a5472dc480e4e6f05d87918800d729e"



